# 异常

标签（空格分隔）： JAVA

---

- 异常处理try...catch...
    ```
try {
    异常代码
    }catch (异常类名 变量名){
    异常处理代码
    }

    ``` 
    
- 程序从try里面代码执行 出现异常，回自动生成一个异常类对象，该异常对象将被提交给Java运行时系统当Java运行时接收到异常对象时，会到catch中去找匹配的异常类，找到后进行异常的处理。程序可以继续往下执行。

```
public class demoui1 {
    public static void main(String[] args) {
        System.out.println("begin");
        me();
        System.out.println("emd");
    }

    public static void me(){
        try {
            int[] ar = {1, 2};
            System.out.println(ar[3]);
        }catch (Exception e)
        {
            System.out.println("outofarray");
            e.printStackTrace();
            System.out.println(e.getMessage());
            System.out.println(e.toString());
        }
    }
}
        /*
        begin
        outofarray
        java.lang.ArrayIndexOutOfBoundsException: 3
            at demoui1.me(demoui1.java:18)
            at demoui1.main(demoui1.java:11)
        3
        java.lang.ArrayIndexOutOfBoundsException: 3
        emd
         */

```
``` 
public class demoui1 {
    public static void main(String[] args) {
        Scanner sc= new Scanner(System.in);
        System.out.println("input scoer");
        int i = sc.nextInt();
        teacher t=new teacher();
        try {
            t.checkSocer(i);
        } catch (Ecsocre ecsocre) {           ecsocre.printStackTrace();        }
    }
}
  class Ecsocre extends  Exception{
    public Ecsocre(){}    public Ecsocre(String message){      super(message);    }
}
class teacher{
    public  void checkSocer(int socer)throws Ecsocre{
        if(socer>100||socer<0)   {       throw new Ecsocre("socer must in 0to 100");
        }else {            System.out.println("zedd");        } 
    }}

```


    
    
    
    





